name: Fetch Feeds

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Check Chromium and Chromedriver versions
        run: |
          chromium-browser --product-version
          chromedriver --version
        
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main script
        run: |
          CHROME_VERSION=$(chromium-browser --product-version) python src/main.py

      - name: Generate webpage
        run: |
          python src/generate_web.py

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}          


      # - name: Commit and push changes
      #   id: commit_and_push
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     message: "action: update feeds"
      #     default_author: github_actions